.TH "Dealer::NegativeNumber" 3 "Fri Jun 7 2019" "texasHoldem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dealer::NegativeNumber
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Dealer\&.h>\fP
.SH "Detailed Description"
.PP 
Definition at line 31 of file Dealer\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for texasHoldem from the source code\&.
