.TH "/home/pete/Dropbox/ScanSnap/School/Byoungmo/2019 Spring/CSC17A/git-repos/LeeByoungmo_CSC_17a_44083/Proj/Proj2/texasHoldem_Ver7/main.cpp" 3 "Fri Jun 7 2019" "texasHoldem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/pete/Dropbox/ScanSnap/School/Byoungmo/2019 Spring/CSC17A/git-repos/LeeByoungmo_CSC_17a_44083/Proj/Proj2/texasHoldem_Ver7/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <ctime>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <cctype>\fP
.br
\fC#include <string>\fP
.br
\fC#include <clocale>\fP
.br
\fC#include 'Card\&.h'\fP
.br
\fC#include 'Dealer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBshowNumPlayers\fP (const \fBDealer\fP *activity)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 38 of file main\&.cpp\&.
.SS "void showNumPlayers (const \fBDealer\fP * activity)"

.PP
Definition at line 85 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for texasHoldem from the source code\&.
